### ISSUE TITLE
Do not load XGAP via LoadPackage

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/fwtree#3]
https://github.com/gap-packages/fwtree/blob/899e8848d1bad9c7dde607c5695fff223bf66ff7/read.g#L11

This line causes a warning
```
#I  fwtree: Do not call `LoadPackage( "xgap", ... )' in the package file
```
while loading. Of course `LoadPackage( "xgap", ... )` does not make sense at all, since it is started via a shell script. The point is only to test whether it is loaded or not.

**Comment by olexandr-konovalov** [comment]
Would be nice to get rid of this warning and make a new release in time for GAP 4.10.

**Comment by fingolfin** [comment]
Would be great if there was an IsPackageLoaded...

**Comment by olexandr-konovalov** [comment]
Maybe it should be... ParGAP (if only), JupyterKernel are potentially interested.
