### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/fwtree#6]
Looking at https://github.com/gap-packages/gap-packages.github.io/issues/9 still having fwtree, I am puzzled that a release published on March 8th does  not have `tst` directory added in February in https://github.com/gap-packages/fwtree/commit/6d3b12dfe5d6fe8a3f40d52f7f93c3d978eb430d#diff-9301c2a72c0f099d0313099f1cd54799. What happened?

**Comment by fingolfin** [comment]
The last release was on March 8th *2018*, while those tests were added in February 2019. I'll make a release with the tests, though.
